### ISSUE TITLE
Python port

### ISSUE THREAD

**Issue by Cerno-b** [APN-Pucky/tyrant_optimize#23]
Hi all, thanks for the great work maintaining the simulator.

I was wondering whether you might be interested in spending some effort to port and continue maintenance of the simulator in Python instead of C++. I think this type of tool lends itself nicely to the language, but the main benefit I can see is to allow running the optimizer as a web service which would allow opening up the tool to a lot more people.

If you are interested in the idea, drop me a note, I would gladly attempt to help in realizing the port as I have over a decade of Python and C++ experience and am familiar with both languages.

**Comment by APN-Pucky** [comment]
Hi, 
I'm currently super busy with finishing my degree.
Nonetheless some notes from my side:

- Python is easier to use, but also a bit slower.
- Migrating the whole code would be quite a lot of work.
- There has been a similar project for Java but I'm not sure about it's state.

If the main interest is to run simulations through/with python instead of editing the simulation code I think the most efficient way would be to use something like pybind11 to link the cpp function to python, thus preserving speed. Then in a phyton/pip server environment one could pip tyrant and get the compiled cpp code too, if I'm not mistaken.

**Comment by Cerno-b** [comment]
Thanks for the quick reply. I did not by any means imply that you shoud do the port by yourself, I was rather offering to work on it, so I was just testing the waters about whether this would be something you might be interested in. I think if such a port was on the table, IMO the only feasible way would be to do a hard switch from pure C++ to python, as maintaining both code bases would be too much effort.

I already took a quick look at the existing code base and I agree it would be quite a chunk of work, that's why I wanted to check with you about what you thought about switching. If I were to put any effort into it, I would need to know whether or not the port would land in the bin afterwards.

I agree on the speed, although we would need to check out how big the difference is. I generally try to avoid mixing C++ and Python since it's much harder to maintain, especially for multiplatform code, but I do have some experience running a C++ dll in python. 

I think the first step would be to actually port some runtime-hungry core portion of the tool to python and do a runtime comparison. If the gap is too large, I would probably not pursue the issue further as maintaining a mixed codebase is probably not worth it. The question of course is how much of a performance hit would be acceptable, e.g. in which simulation scenario a slowdown would actually be painful.

Good luck with finishing your degree, if you could find the time to share some of your thoughts, I might do some experiments on my own, however I'm also super swamped with work at the moment, so I might find some time on the weekends.

**Comment by APN-Pucky** [comment]
Thanks. 
- Regarding maintaining different code bases: I also have the C++ code included in a Android/Java App (though not frequent updated due to little usage), here https://github.com/APN-Pucky/mTUO and there https://play.google.com/store/apps/details?id=de.neuwirthinformatik.Alexander.mTUO . Which would be lost by switching to python.
- Regrading performance: I already did the inverse step of porting to GPU for performance, though also abandoned due to low interest and too much work https://github.com/APN-Pucky/opencl-testing .
- There are some experienced (but not identified) differences between the game and simulation. Another sim would be great to check and get stability/confidence. Though these differences could also be game bugs.

I am afraid I won't be able to help much, besides eventually explaining code pieces.

**Comment by Cerno-b** [comment]
Ah, thanks for the insight. I wasn't aware that there is an Android and Java app. This certainly complicates things. Not sure whether an additional Python implementation would be a huge benefit to the project if it's just another parallel development that has to be kept in sync with the other ones. 

On the other hand, Python code is much simpler to read and unit test, so maybe one use might be as a sort of reference implementation to ensure that the behavior matches that of the game.

I'll keep the idea on the back burner for now, but maybe I'll put some effort into it. I'll let you know in case I have something to show.

Thanks for your work in keeping the sim alive!

**Comment by bestwebdeveloper** [comment]
@Cerno-b 
Just a note: Sim is very cpu-hungry since it does a really lot of calculations. It's effectivenes depends on the available resourses - more cpu you have - less time it will take to sim. C++ is know to be the most effective language in these terms. Python is much simplier in learning but I am afraid it won't be able to achieve the same performance anyway. Compiled code is always faster than scripts. Even the simple `sim` command.

In terms of web-service: for example, I am using TUO as a console utility (basically compiled exectable file) just launching it from the app (which can be written in any language actually). I believe in Python you are able to do the same. The only warning: it will heavily use CPU, so if you plan to run it for example in shared hosting or even VPS, the provider might just block you server/account since it violates their rules (I had such situations, so I had to put web part and sim in different "containers"). That is why you will have to use dedicated server or some self-hosted solution (like sharing you home PC through externat ip). There is a way to limit resourse usage in Linux but again it will drastically reduce the overall performance which is not what you expect from TUO.

Another idea: Since you can use TUO as a console utility just launching it as any other terminal app you can try serve TUO from some home machine or even network of machines to distribute the load while running Python app in the shared web-server which will queue and process requests from the clients. I believe some guilds used some kind of this approach.

So the first thing I would recommend to think of is why do you need it to run through the web? And the second one is whta are you expectations regarding performance and how are you going to precess clients requests. If you will try to run several sims simultaneusly it will slow down them all because the resources are shared.

P.S. Being aware of the probable performance degradation I did a try to port TUO into TypeScript (compiled to JavaScript) to make it able to run it through the web and make me able to improve, maintain it's codebase and experiment with GPU. I have migrated about 90% of the core codebase. It was in most cases just 1-to-1 rewrite exept some concepts which are different for C++ and other languages, like `pointers`. The last thing was to make it work same way as multithreading worked in C++ code. It was pretty tough so I made a break but plan to resume in some time.

**Comment by APN-Pucky** [comment]
On Linux I use `nice -n 10 ...` to avoid freezing from cpu intensive code. I guess web services won't get stuck/slow then, since tuo only uses all remaining resources (see eg. https://askubuntu.com/questions/656771/process-niceness-vs-priority).
Maybe it is of use to someone.

**Comment by themacboy** [comment]
Imo game is over ! No reason to waste energy on it.

**Comment by Cerno-b** [comment]
@bestwebdeveloper Wow, it seems like you guys already put a lot of effort and thought into some of the ideas I had, so it seems the main benefit of what I had in mind has already been thought through and seems to not be very practical in the end. 

I underestimated the computational effort of actually running the sim, so a python implementation for the sole purpose of running it on some web provider's server seems out of the question now even if it turned out to be similarly fast as the existing version. If I had to run my own server with a web interface, then a python implementation would give no additional benefit, since I could simply run the C++ tool in the first place.

So thank you for your input everyone, but I think this idea may not be very useful in the end.

**Comment by APN-Pucky** [comment]
Here an small update. I created python distribution of tuo, using the original cpp source code. However now pip can download the tuo binaries for most linux OS (maybe later windows and mac too).  https://github.com/APN-Pucky/py-tuo 
Compiling it on a specific system probably gives a faster binary.

**Comment by bestwebdeveloper** [comment]
@APN-Pucky Could you please clarify what does it mean? I am not aware of python ecosystem, does this distribution allows to wrap cpp binaries into python package which can be used from python code natively?

**Comment by APN-Pucky** [comment]
Yes, it could be used from python in the future. So far it only adds the possibility to install tuo binaries via:

```
$ pip install tuo
```
