### ISSUE TITLE
Assertion failed error

### ISSUE THREAD

**Issue by baunan** [APN-Pucky/tyrant_optimize#62]
I am getting a error message when running a simulation with a gauntlet I have made. 

```Assertion failed: status->m_card->m_type != CardType::commander, file /home/runner/work/tyrant_optimize/tyrant_optimize/sim.cpp, line 1257```

![image](https://github.com/APN-Pucky/tyrant_optimize/assets/59838425/396bda5f-c634-455d-bb8f-6c89299ea9ea)
[ST06.txt](https://github.com/APN-Pucky/tyrant_optimize/files/11859409/ST06.txt)
By trail and error it looks like the last deck is causing the problem, but can't be for sure atleast the error comes every time I have that deck included, so it should be "easy" to replicate the error I think.

Thanks in advance

**Comment by APN-Pucky** [comment]
Thank you very much for the report. Unfortunately I could not straightforwardly reproduce it. This is because I don't know the contents of the `stedmund.txt`, and I guess it is only a rare deck constructed with your owned cards in the climb process.

I have tried to simulate all decks from `ST06` against `ST06` but neither of them fails the assertion.

I suspect this is somehow a bug in the context of the newly changed skills.

**Comment by baunan** [comment]
[stedmund.txt](https://github.com/APN-Pucky/tyrant_optimize/files/11859953/stedmund.txt)
My bad, I have attached my file with my cards, if you want to have another go. Just old relics cards after 4 years break from this game.
Looks like ```+v```did the trick as it now managed to sim further than it has done before with this gauntlet or the sim took another path so the error don't occure as I am no longer able to reproduce this error.

Anyway thanks for your help.

**Comment by APN-Pucky** [comment]
Thanks. I can reproduce it consistently now with 
```
./tuo-debug "Octane Optimized, Broodmother's Nexus, Demi Constrictor, Sinew Shredder#2, Typhon's Pupil, Myrmidon Remnant, Parapet Welder , Inescapable Detainer#2, Big borra, Bonecrown Drakuzoid" ST06 climb 5000 random +uc endgame 2 brawl seed 1000
```
